version: "3.8"

services:
  backend:
    image: tsaigopal/budget-planner-backend:latest
    container_name: budget-backend
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/budget_planner
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: gopal59681Ab@
    depends_on:
      - db

  frontend:
    image: tsaigopal/budget-planner-frontend:latest
    container_name: budget-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: budget-db
    restart: always
    environment:
      MYSQL_DATABASE: budget_planner
      MYSQL_ROOT_PASSWORD: gopal59681Ab@
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"   # external access if needed

volumes:
  db_data:
